version: '3.4'

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: scoreDei # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: scoreDei # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: scoreDeiDatabase # The PostgreSQL default database (automatically created at first launch)
  command-line:
    build:
     context: .
     dockerfile: Dockerfile
    command: tail -f /dev/null
    links: 
      - database
    volumes:
      - ..:/workspace
    